# Generated by Django 3.0.1 on 2020-01-02 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_text', models.EmailField(max_length=254)),
                ('password_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_text', models.CharField(max_length=200)),
                ('password_text', models.CharField(max_length=50)),
                ('dateofbirth', models.DateTimeField(verbose_name='date published')),
                ('mobile_no', models.IntegerField(default=0)),
                ('city_text', models.CharField(max_length=100)),
                ('state_text', models.CharField(max_length=90)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Login')),
            ],
        ),
    ]
