# Generated by Django 3.0.1 on 2020-01-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200102_1423'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activation',
        ),
    ]
