# Generated by Django 3.0.1 on 2020-01-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_auto_20200104_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
