# Generated by Django 3.0.1 on 2020-01-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_createuserform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUserForm',
        ),
    ]
