# Generated by Django 3.0.1 on 2020-01-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='userotp',
            new_name='user_id',
        ),
    ]
