# Generated by Django 3.0.1 on 2020-01-14 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200113_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='user',
            new_name='username',
        ),
    ]
