# Generated by Django 3.0.1 on 2020-01-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20200114_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='auth_user',
            new_name='user',
        ),
    ]
