# Generated by Django 3.0.1 on 2020-01-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20200115_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='auth_user',
            new_name='user',
        ),
    ]
